name: "Integration Test"
description: "Runs the integration tests"

inputs:
  node-version:
    description: "Node.js version"
    default: "18"
  package-name:
    description: "Package name"
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-environment
      with:
        node-version: ${{ inputs.node-version }}

    - name: ${{ inputs.package-name }} integration tests
      run: yarn workspace @mappersmith-consumer/${{ inputs.package-name }} test:live
      shell: bash
