on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - packages/esm-esbuild/**
      - yarn.lock
      - .yarnrc.yml
      - .tool-versions

concurrency:
  cancel-in-progress: true
  group: "test-${{ github.workflow }}-${{ github.ref_name }}"

jobs:
  call-workflow:
    uses: ./.github/workflows/test-workspace.yml
    with:
      package-name: esm-esbuild
